export const parts = [
  {
    name: "test Teller",
    dateBuy: "16.6.2023",
    dateSold: "",
    category: "teller",
    currency: "EUR",
    purchasingPrice: 1.5,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/teller_adog0o.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: false,
  },
  {
    name: "test Vase",
    dateBuy: "17.6.2023",
    dateSold: "",
    category: "vase",
    currency: "EUR",
    purchasingPrice: 1.3,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/vase_hi8wqg.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: false,
  },
  {
    name: "test Schüssel",
    dateBuy: "18.6.2023",
    dateSold: "",
    category: "schüssel",
    currency: "EUR",
    purchasingPrice: 1.2,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/schuessel_cfpedk.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: false,
  },
  {
    name: "test Figur",
    dateBuy: "19.6.2023",
    dateSold: "",
    category: "figur",
    currency: "EUR",
    purchasingPrice: 2,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687198423/figur_qx22lb.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: false,
  },
  {
    name: "test Teller 2",
    dateBuy: "16.6.2023",
    dateSold: "20.6.2023",
    category: "teller",
    currency: "EUR",
    purchasingPrice: 1.5,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/teller_adog0o.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: true,
  },
  {
    name: "test Vase 2",
    dateBuy: "17.6.2023",
    dateSold: "21.6.2023",
    category: "vase",
    currency: "EUR",
    purchasingPrice: 1.3,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/vase_hi8wqg.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: false,
    isSold: true,
  },
  {
    name: "test Schüssel 2",
    dateBuy: "18.6.2023",
    dateSold: "",
    category: "schüssel",
    currency: "EUR",
    purchasingPrice: 1.2,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687168427/test/schuessel_cfpedk.jpg",
    partOrigin: "test Origin",
    inAssembler: true,
    isAssembled: false,
    isSold: false,
  },
  {
    name: "test Figur 2",
    dateBuy: "19.6.2023",
    dateSold: "",
    category: "figur",
    currency: "EUR",
    purchasingPrice: 2,
    imgUrl:
      "https://res.cloudinary.com/dn4pswuzt/image/upload/v1687198423/figur_qx22lb.jpg",
    partOrigin: "test Origin",
    inAssembler: false,
    isAssembled: true,
    isSold: false,
  },
];
